name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v18

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the site
        run: nix develop --command mkdocs build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'site/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
